language: node_js
node_js:
  - '11.0'

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng lint
  - ng test --watch=false
  - ng build --prod

deploy:
  edge: true
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/video-gamer
  on:

after_success: cp .htaccess dist/video-gamer
