# language: node_js
# node_js:
#   - '11.0'
# branches:
#   only:
#     - master
# before_script:
#   - npm install -g @angular/cli
# script:
#   - npm install
#   - npm run build
# deploy:
#   skip_cleanup: true
#   provider: gh-pages
#   token:
#     secure: ''

language: node_js
node_js:
  - '11.0'

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - yarn global add @angular/cli

cache:
  yarn: true
  directories:
    - node_modules

script:
  - ng build --prod

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on:
